import os
from datetime import datetime

import aiofiles
from database.memory_db import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import FileResponse
from loguru import logger
from pydantic import BaseModel

from config import settings
from database.connection import get_database
from models import ReportDocument

router = APIRouter(tags=["Reports"])

REPORT_DIR = settings.REPORT_DIR

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>APK Threat Analysis Report</title>
<style>
  @page {{ size: A4; margin: 2cm; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #222; }}
  h1 {{ color: #c0392b; border-bottom: 2px solid #c0392b; padding-bottom: 5px; }}
  h2 {{ color: #2c3e50; margin-top: 25px; }}
  h3 {{ color: #34495e; }}
  .header {{ text-align: center; margin-bottom: 30px; }}
  .header h1 {{ border: none; font-size: 22pt; }}
  .score-box {{ display: inline-block; padding: 10px 25px; border-radius: 8px; color: #fff; font-size: 18pt; font-weight: bold; margin: 10px 0; }}
  .score-critical {{ background: #c0392b; }}
  .score-high {{ background: #e74c3c; }}
  .score-medium {{ background: #e67e22; }}
  .score-low {{ background: #f39c12; }}
  .score-safe {{ background: #27ae60; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 10pt; }}
  th {{ background: #34495e; color: #fff; }}
  tr:nth-child(even) {{ background: #f9f9f9; }}
  .finding {{ background: #fdf2e9; border-left: 4px solid #e67e22; padding: 8px 12px; margin: 5px 0; }}
  .ioc {{ background: #fdedec; border-left: 4px solid #c0392b; padding: 8px 12px; margin: 5px 0; }}
  .footer {{ margin-top: 40px; font-size: 9pt; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }}
  .meta {{ color: #555; font-size: 10pt; }}
</style>
</head>
<body>
<div class="header">
  <h1>APK Threat Analysis Report</h1>
  <p class="meta">Case #{{ case_number }} | Generated: {{ generated_at }}</p>
</div>

<h2>Case Information</h2>
<table>
  <tr><td>Package Name</td><td>{{ package_name }}</td></tr>
  <tr><td>File Name</td><td>{{ file_name }}</td></tr>
  <tr><td>SHA256</td><td style="font-family:monospace;font-size:9pt">{{ sha256 }}</td></tr>
  <tr><td>File Size</td><td>{{ file_size }}</td></tr>
</table>

<h2>Risk Assessment</h2>
<p>
  <span class="score-box score-{{ score_class }}">{{ overall_score }}/100 — {{ category }}</span>
</p>
<h3>Component Scores</h3>
<table>
  <tr><th>Component</th><th>Score</th></tr>
  <tr><td>Permissions</td><td>{{ perm_score }}</td></tr>
  <tr><td>IOCs</td><td>{{ ioc_score }}</td></tr>
  <tr><td>C2 Detection</td><td>{{ c2_score }}</td></tr>
  <tr><td>Behavior</td><td>{{ behavior_score }}</td></tr>
  <tr><td>Anti-Analysis</td><td>{{ anti_score }}</td></tr>
</table>
<p><strong>ML Classification:</strong> {{ ml_family }} ({{ ml_confidence }})</p>

<h2>Permissions</h2>
{% if permissions %}
<table>
  <tr><th>Permission</th><th>Category</th></tr>
  {% for p in permissions %}
  <tr><td>{{ p.name }}</td><td>{{ p.category }}</td></tr>
  {% endfor %}
</table>
{% else %}
<p>No permissions detected.</p>
{% endif %}

<h2>Indicators of Compromise</h2>
<h3>URLs ({{ urls|length }})</h3>
{% if urls %}
  {% for url in urls %}<div class="ioc">{{ url }}</div>{% endfor %}
{% else %}
<p>None found.</p>
{% endif %}

<h3>IPs ({{ ips|length }})</h3>
{% if ips %}
  {% for ip in ips %}<div class="ioc">{{ ip }}</div>{% endfor %}
{% else %}
<p>None found.</p>
{% endif %}

<h3>Domains ({{ domains|length }})</h3>
{% if domains %}
  {% for d in domains %}<div class="ioc">{{ d }}</div>{% endfor %}
{% else %}
<p>None found.</p>
{% endif %}

<h2>C2 Analysis</h2>
{% if dga_domains %}
<h3>DGA Domains</h3>
{% for d in dga_domains %}<div class="finding">{{ d }}</div>{% endfor %}
{% endif %}
{% if ioc_matches %}
<h3>IOC Matches</h3>
{% for m in ioc_matches %}<div class="finding">{{ m }}</div>{% endfor %}
{% endif %}
{% if mitre_techniques %}
<h3>MITRE ATT&CK Techniques</h3>
{% for t in mitre_techniques %}<div class="finding">{{ t }}</div>{% endfor %}
{% endif %}

{% if yara_matches %}
<h2>YARA Matches</h2>
{% for y in yara_matches %}
<div class="finding"><strong>{{ y.rule_name }}</strong> ({{ y.severity }}) — {{ y.description }}</div>
{% endfor %}
{% endif %}

<div class="footer">
  <p>Generated by APK Threat Analysis Platform v1.0 | This report is for authorized security analysis purposes only.</p>
</div>
</body>
</html>"""


class GenerateReportRequest(BaseModel):
    analysis_id: str


def _score_class(score: float) -> str:
    if score >= 71:
        return "critical"
    elif score >= 56:
        return "high"
    elif score >= 41:
        return "medium"
    elif score >= 16:
        return "low"
    return "safe"


@router.post("/reports/generate")
async def generate_report(req: GenerateReportRequest, db=Depends(get_database)):
    try:
        analysis = await db.analysis_results.find_one({"_id": ObjectId(req.analysis_id)})
        if not analysis:
            analysis = await db.analysis_results.find_one({"apk_id": req.analysis_id})
    except Exception:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid analysis ID")

    if not analysis:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Analysis not found")

    apk_id = str(analysis.get("apk_id") or req.analysis_id)
    apk = await db.apks.find_one({"_id": ObjectId(apk_id)})

    ts = analysis.get("threat_score", {})
    sa = analysis.get("static_analysis", {})
    c2 = analysis.get("c2_detection", {})

    overall_score = ts.get("overall_score", 0)
    category = ts.get("category", "Unknown")
    comp = ts.get("components", {})
    mlc = ts.get("ml_classification", {})

    ctx = {
        "case_number": f"APK-{req.analysis_id[:8].upper()}",
        "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        "package_name": (apk or {}).get("package_name", "N/A"),
        "file_name": (apk or {}).get("original_filename", "N/A"),
        "sha256": (apk or {}).get("sha256", "N/A"),
        "file_size": f"{((apk or {}).get('file_size_bytes', 0) / 1024 / 1024):.2f} MB",
        "overall_score": overall_score,
        "score_class": _score_class(overall_score),
        "category": category,
        "perm_score": comp.get("permission_score", {}).get("score", 0) if isinstance(comp.get("permission_score"), dict) else comp.get("permission_score", 0),
        "ioc_score": comp.get("ioc_score", {}).get("score", 0) if isinstance(comp.get("ioc_score"), dict) else comp.get("ioc_score", 0),
        "c2_score": comp.get("c2_score", {}).get("score", 0) if isinstance(comp.get("c2_score"), dict) else comp.get("c2_score", 0),
        "behavior_score": comp.get("behavior_score", {}).get("score", 0) if isinstance(comp.get("behavior_score"), dict) else comp.get("behavior_score", 0),
        "anti_score": comp.get("anti_analysis_score", {}).get("score", 0) if isinstance(comp.get("anti_analysis_score"), dict) else comp.get("anti_analysis_score", 0),
        "ml_family": mlc.get("prediction", "Unknown"),
        "ml_confidence": f"{mlc.get('confidence', 0) * 100:.1f}%" if isinstance(mlc.get("confidence"), (int, float)) else "N/A",
        "permissions": sa.get("permissions", []),
        "urls": sa.get("urls", []),
        "ips": sa.get("ips", []),
        "domains": sa.get("domains", []),
        "dga_domains": c2.get("dga_domains", []),
        "ioc_matches": c2.get("ioc_matches", []),
        "mitre_techniques": c2.get("mitre_techniques", []),
        "yara_matches": analysis.get("yara_matches", []),
    }

    try:
        from jinja2 import Template
        template = Template(REPORT_HTML_TEMPLATE)
        html_content = template.render(**ctx)
    except Exception as e:
        logger.exception("Template rendering failed")
        html_content = "<html><body><h1>Report Generation Error</h1><p>Unable to render the report template.</p></body></html>"

    os.makedirs(REPORT_DIR, exist_ok=True)
    report_filename = f"report_{req.analysis_id}.html"
    report_path = os.path.join(REPORT_DIR, report_filename)

    pdf_generated = False
    try:
        from weasyprint import HTML
        pdf_filename = f"report_{req.analysis_id}.pdf"
        pdf_path = os.path.join(REPORT_DIR, pdf_filename)
        HTML(string=html_content).write_pdf(pdf_path)
        report_path = pdf_path
        report_filename = pdf_filename
        pdf_generated = True
        logger.info(f"PDF report generated: {pdf_path}")
    except ImportError:
        logger.info("WeasyPrint not available, saving as HTML")
        async with aiofiles.open(report_path, "w", encoding="utf-8") as f:
            await f.write(html_content)
    except Exception as e:
        logger.warning(f"PDF generation failed ({e}), falling back to HTML")
        async with aiofiles.open(report_path, "w", encoding="utf-8") as f:
            await f.write(html_content)

    import hashlib
    sha256_hash = hashlib.sha256()
    async with aiofiles.open(report_path, "rb") as f:
        while True:
            chunk = await f.read(1024 * 1024)
            if not chunk:
                break
            sha256_hash.update(chunk)
    file_hash = sha256_hash.hexdigest()

    report_doc = ReportDocument(
        apk_id=apk_id,
        analysis_id=req.analysis_id,
        template_used="default",
        file_path=report_path,
        sha256=file_hash,
    )

    result = await db.reports.insert_one(report_doc.to_dict())
    report_id = str(result.inserted_id)

    return {
        "id": report_id,
        "analysis_id": req.analysis_id,
        "filename": report_filename,
        "format": "pdf" if pdf_generated else "html",
        "sha256": file_hash,
        "generated_at": datetime.utcnow().isoformat(),
    }


@router.get("/reports/{report_id}")
async def get_report(report_id: str, db=Depends(get_database)):
    try:
        doc = await db.reports.find_one({"_id": ObjectId(report_id)})
    except Exception:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid report ID")

    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")

    doc["_id"] = str(doc["_id"])
    return doc


@router.get("/reports/{report_id}/download")
async def download_report(report_id: str, db=Depends(get_database)):
    try:
        doc = await db.reports.find_one({"_id": ObjectId(report_id)})
    except Exception:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid report ID")

    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")

    file_path = doc.get("file_path")
    if not file_path or not os.path.isfile(file_path):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report file not found on disk")

    report_root = os.path.abspath(REPORT_DIR)
    resolved_path = os.path.abspath(file_path)
    if os.path.commonpath([report_root, resolved_path]) != report_root:
        logger.warning(f"Blocked report download outside report dir: {resolved_path}")
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Report path is not allowed")

    filename = os.path.basename(resolved_path)
    media_type = "application/pdf" if filename.endswith(".pdf") else "text/html"

    return FileResponse(
        path=resolved_path,
        filename=filename,
        media_type=media_type,
    )


@router.get("/reports")
async def list_reports(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    db=Depends(get_database),
):
    skip = (page - 1) * limit
    total = await db.reports.count_documents({})

    cursor = db.reports.find({}).sort([("generated_at", -1)]).skip(skip).limit(limit)
    reports = []
    async for doc in cursor:
        doc["_id"] = str(doc["_id"])
        reports.append(doc)

    return {
        "total": total,
        "page": page,
        "limit": limit,
        "reports": reports,
    }


@router.get("/reports/history")
async def get_report_history(db=Depends(get_database)):
    cursor = db.reports.find(
        {},
        {"_id": 1, "apk_id": 1, "template_used": 1, "generated_at": 1, "file_path": 1},
    ).sort([("generated_at", -1)]).limit(50)

    history = []
    async for doc in cursor:
        doc["_id"] = str(doc["_id"])
        history.append(doc)

    return {"history": history}


@router.get("/reports/templates")
async def list_templates():
    return {
        "templates": [
            {"id": "default", "name": "Default Report", "description": "Standard forensic analysis report with risk score, permissions, IOCs, and C2 findings"},
        ]
    }
